# Generated by Django 3.2.6 on 2021-11-29 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='firstName',
            field=models.CharField(default='', max_length=100, verbose_name='first Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='lastName',
            field=models.CharField(default='', max_length=100, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
