# Generated by Django 3.2.6 on 2021-11-29 20:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20211129_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('deleted_status', models.BooleanField(default=False)),
                ('doneAt', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
                ('done_by', models.CharField(editable=False, max_length=255)),
                ('last_updated_by', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('contact_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
            ],
            options={
                'db_table': 'contact_phone',
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('deleted_status', models.BooleanField(default=False)),
                ('doneAt', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
                ('done_by', models.CharField(editable=False, max_length=255)),
                ('last_updated_by', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('contact_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
            ],
            options={
                'db_table': 'contact_email',
            },
        ),
    ]
