# Generated by Django 3.2.6 on 2021-11-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20211129_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactemail',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
