# Generated by Django 3.2.6 on 2021-11-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20211129_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactemail',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
